apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  namespace: reservas-py
  labels:
    apipy: reservas
spec:
  replicas: 2
  selector:
    matchLabels:
      apipy: reservas
  template:
    metadata:
      labels:
        apipy: reservas
    spec:
      containers:
      - name: backend-reservas
        image: magodocker/backend-reservas-py:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-reservas
  namespace: reservas-py
spec:
  selector:
    app: fastapi-demo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 7070
